services:
  postgresql-16:
    image: postgres:16
    restart: always


    container_name: postgresql-16
    hostname: postgresql-16

    environment:
      POSTGRES_DB: hajime_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - '5432:5432'

    networks:
      - hajime_network

    volumes:
      - hajime_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  hajime_data:

networks:
  hajime_network:
