services:
  postgresql-16:
    image: postgres:16
    restart: always

    container_name: postgresql-16
    hostname: postgresql-16

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    networks:
      - hajime_network

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - hajime_data-postgres:/var/lib/postgresql/data

  minio-storage:
    image: quay.io/minio/minio:RELEASE.2024-10-29T16-01-48Z
    restart: always

    container_name: minio-storage
    hostname: minio-storage

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server --console-address ":${MINIO_CONSOLE_PORT}" /data

    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}

    networks:
      - hajime_network

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - hajime_data-minio:/data

volumes:
  hajime_data-minio:
  hajime_data-postgres:

networks:
  hajime_network:
