export { default as userSeed } from './user.seed'
export { default as personalInfoSeed } from './personalInfo.seed'
export { default as loginSeed } from './login.seed'
export { default as exerciseCategorySeed } from './exerciseCategory.seed'
export { default as classSeed } from './class.seed'
export { default as checkinSeed } from './checkin.seed'